services:
  db:
    image: timescale/timescaledb:latest-pg18
    restart: always
    shm_size: 512mb
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=quant_platform
    command:
      - postgres
      - -c
      - shared_buffers=512MB
      - -c
      - effective_cache_size=1536MB
      - -c
      - work_mem=8MB
      - -c
      - maintenance_work_mem=256MB
      - -c
      - max_wal_size=2GB
      - -c
      - checkpoint_completion_target=0.9
      - -c
      - max_connections=50
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data:
